var object = {
      NONE :{name:"None"},
      STEPSUP : {name:"Steps Up",frame:0},
      STEPSDOWN : {name:"Steps Down",frame:1},
      TRAPDOOR : {name:"Trapdoor",frame:2},
      HOLE : {name:"Hole",frame:3},
      TELEPORT :{name:"Teleport",frame:4},
      DOOR : {name:"Door",frame:5},
      LOCKEDDOOR : {name:"Locked Door",frame:6},
      TRAPPEDDOOR : {name:"Trapped Door",frame:7},
      SECRETDOOR : {name:"Secret Door",frame:8},
      GATE : {name:"Gate",frame:9},
      LEVER : {name:"Lever",frame:10},
      PRESSUREPLATE : {name:"Pressure Plate",frame:11},
      CHEST : {name:"Chest",frame:12},
      LOCKEDCHEST : {name:"Locked Chest",frame:13},
      TRAPPEDCHEST : {name:"Trapped Chest",frame:14},
      OPENCHEST : {name:"Open Chest",frame:15},
      TRASHHEAP : {name:"Trash Heap",frame:16},
      EMPTYHEAP : {name:"Empty Trash Heap",frame:17},
      BOOKCASE : {name:"Bookcase",frame:18},
      EMPTYBOOKCASE : {name:"Empty Bookcase",frame:19},
      FOUNTAIN : {name:"Fountain",frame:20},
      DRYFOUNTAIN : {name:"Dry Fountain",frame:21},
      BED : {name:"Bed",frame:22},
      CTREE : {name:"Tree",frame:23},
      DTREE : {name:"Tree",frame:24},
      CACTUS : {name:"Cactus",frame:25},
      APPLETREE : {name:"Apple Tree",frame:26}
    }
    